name = "ti2"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
vxml = { "path" = "../wly/vxml" }
writerly = { "path" = "../wly/writerly" }
desugaring = { "path" = "../wly/desugaring" }
either_or = { "path" = "../either_or" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
on = ">= 1.1.0 and < 2.0.0"
splitter = ">= 1.1.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
colours = ">= 0.3.0 and < 1.0.0"
input = ">= 1.0.1 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
dirtree = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
